# Generated by Django 4.0.3 on 2022-03-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentid', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门唯一标识，非ID')),
                ('department_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门名称')),
                ('department_level', models.IntegerField(default=1, verbose_name='部门级别（0级部门）')),
                ('department_parent', models.IntegerField(blank=True, null=True, verbose_name='父级部门ID')),
            ],
        ),
        migrations.CreateModel(
            name='MailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='用户邮箱')),
                ('token', models.CharField(max_length=255, verbose_name='邮箱token')),
            ],
        ),
        migrations.CreateModel(
            name='UserDepartRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(verbose_name='部门ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('joined_time', models.DateTimeField(auto_now_add=True, verbose_name='员工加入部门时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, verbose_name='用户唯一标识，非ID，登录使用')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户密码')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户英文名')),
                ('aliasname', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户中文名')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='用户邮箱')),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='用户手机号')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户的位置，座位号')),
                ('head_images', models.URLField(blank=True, max_length=255, null=True, verbose_name='用户头像')),
                ('joined_time', models.DateTimeField(blank=True, null=True, verbose_name='账号创建时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, null=True, verbose_name='用户最后一次登录的时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, verbose_name='用户最后一次登录的ip')),
                ('is_admin', models.BooleanField(default=0, verbose_name='是否为管理员')),
                ('is_active', models.BooleanField(default=0, verbose_name='是否禁用')),
                ('last_set_pwd_time', models.DateTimeField(blank=True, null=True, verbose_name='密码最后一次设置的时间')),
                ('last_set_pwd_ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, verbose_name='密码最后一次设置的ip')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, verbose_name='用户登录账号')),
                ('token', models.CharField(max_length=255, verbose_name='用户token')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='token创建时间')),
            ],
        ),
    ]
