# Generated by Django 4.0.3 on 2022-03-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_remove_usertoken_id_alter_usertoken_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='部门唯一标识'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户唯一标识，登录使用'),
        ),
    ]
