# Generated by Django 4.0.3 on 2022-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtoken',
            name='apply_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='申请邮箱token的ip'),
        ),
        migrations.AddField(
            model_name='mailtoken',
            name='userid',
            field=models.CharField(default='test', max_length=30, verbose_name='用户登录账号'),
        ),
    ]
