# Generated by Django 4.0.3 on 2022-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0005_mailtoken_apply_ip_mailtoken_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='mailtoken',
            name='userid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户登录账号'),
        ),
    ]
