# Generated by Django 4.0.3 on 2022-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_remove_mailtoken_id_alter_mailtoken_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机号'),
        ),
    ]
