# Generated by Django 4.0.3 on 2022-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='用户手机号'),
        ),
    ]
